//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftShopApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TableProduct
    {
        public int ProductID { get; set; }

        [Required(ErrorMessage ="Bu kýsým boþ býrakýlamaz")]
        public string ProductName { get; set; }

        [Required(ErrorMessage = "Bu kýsým boþ býrakýlamaz")]
        public int ProductPrice { get; set; }
    }
}
